"""empty message

Revision ID: f63f351775e4
Revises: 2d0550b35a19
Create Date: 2018-12-29 17:39:36.923222

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f63f351775e4'
down_revision = '2d0550b35a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.String(length=300), nullable=False))
    op.alter_column('user', 'first_name',
                    existing_type=sa.VARCHAR(length=300),
                    nullable=True)
    op.alter_column('user', 'last_name',
                    existing_type=sa.VARCHAR(length=300),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
                    existing_type=sa.VARCHAR(length=300),
                    nullable=False)
    op.alter_column('user', 'first_name',
                    existing_type=sa.VARCHAR(length=300),
                    nullable=False)
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###
